# Generated by Django 6.0.3 on 2026-03-18 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('objectives', models.TextField()),
                ('pico_population', models.TextField(blank=True)),
                ('pico_intervention', models.TextField(blank=True)),
                ('pico_comparison', models.TextField(blank=True)),
                ('pico_outcomes', models.TextField(blank=True)),
                ('inclusion_criteria', models.TextField(blank=True)),
                ('exclusion_criteria', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('upload_window', 'Upload Window'), ('paper_confirmation', 'Paper Confirmation'), ('done', 'Done')], default='queued', max_length=20)),
                ('stage_progress', models.JSONField(blank=True, default=dict)),
                ('scaffold', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('authors', models.TextField(blank=True)),
                ('abstract', models.TextField(blank=True)),
                ('publication_year', models.IntegerField(blank=True, null=True)),
                ('journal', models.CharField(blank=True, max_length=255)),
                ('doi', models.CharField(blank=True, db_index=True, max_length=255)),
                ('scopus_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('url', models.URLField(blank=True)),
                ('keywords', models.TextField(blank=True)),
                ('citation_count', models.IntegerField(default=0)),
                ('ta_decision', models.CharField(choices=[('included', 'Included'), ('excluded', 'Excluded'), ('flagged', 'Flagged')], default='flagged', max_length=10)),
                ('ta_confidence', models.FloatField(default=0.0)),
                ('ta_reason', models.TextField(blank=True)),
                ('pdf_path', models.FileField(blank=True, upload_to='papers/pdfs/')),
                ('fulltext_retrieved', models.BooleanField(default=False)),
                ('pdf_text', models.TextField(blank=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='reviews.review')),
            ],
        ),
    ]
