# Generated by Django 6.0.3 on 2026-03-18 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('type', models.CharField(choices=[('descriptive', 'Descriptive'), ('comparative', 'Comparative'), ('causal', 'Causal'), ('exploratory', 'Exploratory')], default='descriptive', max_length=12)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_questions', to='reviews.review')),
            ],
        ),
    ]
