# Generated by Django 6.0.3 on 2026-03-18 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_researchquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_string', models.TextField()),
                ('focus', models.CharField(choices=[('core', 'Core'), ('synonyms', 'Synonyms'), ('constructs', 'Constructs'), ('population', 'Population'), ('outcomes', 'Outcomes')], max_length=20)),
                ('rationale', models.TextField(blank=True)),
                ('is_executed', models.BooleanField(default=False)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_queries', to='reviews.review')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('review', 'focus'), name='unique_review_focus_query')],
            },
        ),
    ]
