# Generated by Django 6.0.3 on 2026-03-18 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_searchquery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchquery',
            name='focus',
            field=models.CharField(choices=[('core', 'Core'), ('constructs', 'Constructs'), ('population', 'Population'), ('outcomes', 'Outcomes')], max_length=20),
        ),
    ]
