# Generated by Django 6.0.3 on 2026-03-18 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_searchquery_focus'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='access_date',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='paper',
            name='end_page',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='paper',
            name='issn',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='paper',
            name='language',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='paper',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='number',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='paper',
            name='publisher',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='paper',
            name='start_page',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='paper',
            name='type_of_work',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='paper',
            name='volume',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
