# Generated by Django 6.0.3 on 2026-03-18 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_paper_access_date_paper_end_page_paper_issn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchquery',
            name='imported_records',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='searchquery',
            name='missing_abstracts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='searchquery',
            name='ris_file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='searchquery',
            name='ris_uploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='searchquery',
            name='ris_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
