# Generated by Django 6.0.3 on 2026-03-18 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_searchquery_imported_records_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='ta_decision',
            field=models.CharField(blank=True, choices=[('included', 'Included'), ('excluded', 'Excluded'), ('flagged', 'Flagged'), ('missing_abs', 'Missing_Abs')], default=None, max_length=20, null=True),
        ),
    ]
