# Generated by Django 6.0.3 on 2026-03-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_alter_paper_ta_decision'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='screening_conflict',
            field=models.BooleanField(default=False),
        ),
    ]
