# Generated by Django 6.0.3 on 2026-03-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0008_paper_screening_conflict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='ta_decision',
            field=models.CharField(blank=True, choices=[('included', 'Included'), ('excluded', 'Excluded'), ('flagged', 'Flagged'), ('temp_flag', 'Temp_Flag'), ('manual_flag', 'Manual_Flag'), ('missing_abs', 'Missing_Abs')], default=None, max_length=20, null=True),
        ),
    ]
