# Generated by Django 6.0.3 on 2026-03-20 04:22

from django.db import migrations, models


def set_existing_nulls_to_not_processed(apps, schema_editor):
    Paper = apps.get_model('reviews', 'Paper')
    Paper.objects.filter(ta_decision__isnull=True).update(ta_decision='not_processed')


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0009_alter_paper_ta_decision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='ta_decision',
            field=models.CharField(blank=True, choices=[('included', 'Included'), ('excluded', 'Excluded'), ('flagged', 'Flagged'), ('temp_flag', 'Temp_Flag'), ('manual_flag', 'Manual_Flag'), ('missing_abs', 'Missing_Abs'), ('not_processed', 'Not_Processed')], default='not_processed', max_length=20, null=True),
        ),
        migrations.RunPython(set_existing_nulls_to_not_processed, migrations.RunPython.noop),
    ]
