# Generated by Django 6.0.3 on 2026-03-20 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_alter_paper_ta_decision'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='pdf_source',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
