# Generated by Django 6.0.3 on 2026-03-20 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0011_paper_pdf_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='grobid_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='grobid_parsed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paper',
            name='grobid_sections',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='paper',
            name='processed_pdf_grobid',
            field=models.BooleanField(default=False),
        ),
    ]
