# Generated by Django 6.0.3 on 2026-03-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0012_paper_grobid_error_paper_grobid_parsed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='mineru_batch_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='paper',
            name='mineru_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='mineru_markdown',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='mineru_parsed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paper',
            name='mineru_status',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='paper',
            name='processed_pdf_mineru',
            field=models.BooleanField(default=False),
        ),
    ]
