# Generated by Django 6.0.3 on 2026-03-21 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0013_paper_mineru_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='ref_delete_done',
            field=models.BooleanField(default=False),
        ),
    ]
