# Generated by Django 6.0.3 on 2026-03-22 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0014_paper_ref_delete_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='full_text_cache_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='paper',
            name='full_text_cache_status',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='paper',
            name='full_text_decision',
            field=models.CharField(choices=[('not_screened', 'Not_Screened'), ('included', 'Included'), ('excluded', 'Excluded'), ('manual_flag', 'Manual_Flag')], default='not_screened', max_length=20),
        ),
        migrations.AddField(
            model_name='paper',
            name='full_text_exclusion_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='full_text_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='full_text_rq1_findings_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='full_text_rq2_findings_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='full_text_rq_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='paper',
            name='full_text_screened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='full_text_screening_error',
            field=models.TextField(blank=True),
        ),
    ]
