# Generated by Django 6.0.3 on 2026-03-22 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0015_paper_fulltext_screening_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='full_text_screening_status',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
