# Generated by Django 6.0.3 on 2026-03-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0016_paper_full_text_screening_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='full_text_summery',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='paper',
            name='full_text_summery_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='full_text_summery_status',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='paper',
            name='full_text_summery_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
