# Generated by Django 6.0.3 on 2026-03-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0017_paper_full_text_summery_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='full_text_extraction',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='paper',
            name='full_text_quality',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
