# Generated by Django 6.0.3 on 2026-03-25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0018_paper_full_text_extraction_and_quality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='grobid_error',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='grobid_parsed',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='grobid_sections',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='processed_pdf_grobid',
        ),
    ]
