# Generated by Django 6.0.3 on 2026-03-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0019_remove_grobid_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='full_text_screening_model',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='paper',
            name='full_text_screening_provider',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
