# Generated by Django 6.0.3 on 2026-03-25 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0020_paper_full_text_screening_provider_and_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='full_text_rq_findings_map',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
