# Generated by Django 6.0.3 on 2026-03-25 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0021_paper_full_text_rq_findings_map'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='pdf_text',
        ),
    ]
