# Generated by Django 6.0.3 on 2026-03-25 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0022_remove_paper_pdf_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='full_text_cache_id',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='full_text_cache_status',
        ),
    ]
