# Generated by Django 6.0.3 on 2026-03-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0023_remove_paper_full_text_cache_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='theme_synthesis',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='review',
            name='theme_synthesis_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='review',
            name='theme_synthesis_status',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='review',
            name='theme_synthesis_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
