# Generated by Django 6.0.3 on 2026-03-25 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0024_review_theme_synthesis_review_theme_synthesis_error_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeSynthesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_name_locked', models.CharField(max_length=255)),
                ('evidence_grade', models.CharField(choices=[('Established', 'Established'), ('Emerging', 'Emerging'), ('Contested', 'Contested'), ('Insufficient', 'Insufficient')], max_length=32)),
                ('paper_count', models.IntegerField(default=0)),
                ('pct_of_corpus', models.FloatField(default=0.0)),
                ('finding_direction', models.CharField(blank=True, max_length=32)),
                ('designs_represented', models.JSONField(blank=True, default=list)),
                ('grade_rationale', models.TextField(blank=True)),
                ('theme_description', models.TextField(blank=True)),
                ('order_index', models.IntegerField(default=0)),
                ('advocate_notes', models.TextField(blank=True)),
                ('critic_notes', models.TextField(blank=True)),
                ('reconciler_notes', models.TextField(blank=True)),
                ('papers', models.ManyToManyField(blank=True, related_name='themes', to='reviews.paper')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theme_syntheses', to='reviews.review')),
            ],
            options={
                'ordering': ['order_index', '-paper_count', 'id'],
                'constraints': [models.UniqueConstraint(fields=('review', 'theme_name_locked'), name='unique_review_locked_theme_name')],
            },
        ),
    ]
