# Generated by Django 6.0.3 on 2026-03-25 19:29

from django.db import migrations, models


def _copy_legacy_scaffold_to_new_fields(apps, schema_editor):
    Review = apps.get_model('reviews', 'Review')
    for review in Review.objects.all().iterator():
        legacy = review.scaffold if isinstance(review.scaffold, dict) else {}
        scaffold_data = dict(legacy)
        preamble = ''
        if 'scaffold_preamble_template' in scaffold_data:
            preamble = str(scaffold_data.get('scaffold_preamble_template') or '')
            scaffold_data.pop('scaffold_preamble_template', None)

        review.scaffold_data = scaffold_data
        review.scaffold_preamble_template = preamble
        review.save(update_fields=['scaffold_data', 'scaffold_preamble_template'])


def _noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0025_themesynthesis'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='scaffold_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='review',
            name='scaffold_preamble_template',
            field=models.TextField(blank=True),
        ),
        migrations.RunPython(_copy_legacy_scaffold_to_new_fields, _noop_reverse),
    ]
