# Generated by Django 6.0.3 on 2026-03-25 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0026_review_scaffold_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='scaffold',
        ),
    ]
