# Generated by Django 6.0.3 on 2026-03-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0027_remove_review_scaffold'),
    ]

    operations = [
        migrations.AddField(
            model_name='themesynthesis',
            name='reconciled_text',
            field=models.TextField(blank=True),
        ),
    ]
