# Generated by Django 6.0.3 on 2026-04-08 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0028_themesynthesis_reconciled_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='title_screening_confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='paper',
            name='title_screening_decision',
            field=models.CharField(choices=[('title_screening_included', 'Title_Screening_Included'), ('title_screening_excluded', 'Title_Screening_Excluded'), ('title_screening_uncertain', 'Title_Screening_Uncertain'), ('title_screening_not_processed', 'Title_Screening_Not_Processed')], db_index=True, default='title_screening_not_processed', max_length=40),
        ),
        migrations.AddField(
            model_name='paper',
            name='title_screening_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='title_screening_model',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='paper',
            name='title_screening_provider',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='paper',
            name='title_screening_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='title_screening_screened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='title_screening_status',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
