# Generated by Django 6.0.3 on 2026-04-13 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0039_litpaperassignment_and_assignment_status_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='title_screening_decision',
            field=models.CharField(choices=[('title_screening_included', 'Title_Screening_Included'), ('title_screening_excluded', 'Title_Screening_Excluded'), ('title_screening_uncertain', 'Title_Screening_Uncertain'), ('manual_titles', 'Manual_Titles'), ('title_screening_not_processed', 'Title_Screening_Not_Processed')], db_index=True, default='title_screening_not_processed', max_length=40),
        ),
    ]
