# Generated by Django 6.0.3 on 2026-04-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0041_review_theoretical_lens'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='full_text_tccm',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
